export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
// These styles apply to every route in the application
import './globals.css'

import Navbar from '@/components/Nav';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  )
}
